spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
#    static-path-pattern: /assets/


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.beautifulsoup.bean.db
server:
  port: 8881



